# Generated by Django 4.1.5 on 2023-01-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institute_Management_App", "0004_department_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="Total_Faculty",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="Chief_Guest",
            field=models.CharField(max_length=20),
        ),
    ]
